### ISSUE TITLE
Add state saving.

### ISSUE THREAD

**Issue by Martenfur** [Martenfur/TabletFriend#2]
The program must save its position on the screen and current layout between launches. Maybe add a simple config file with all that data. Avoid putting anything in the registry.

**Comment by alfish2000** [comment]
Maybe with a .Net *.config file next to the exe.
Or in some user AppData location?
Maybe depends on the long-term goal how the exe, layouts, config should be deployed/installed.
I mean it could be a "PortableApp" where everything is contained in a root folder.
Or should it be installed to Program Files where the *.config and layouts would have to be stored in User AppData or so.
