### ISSUE TITLE
ArtRage toolbar created

### ISSUE THREAD

**Issue by captainflasmr** [Martenfur/TabletFriend#22]
Hello there, no issue to report!, I have been playing around with the tool using ArtRage and have built a toolbar that seems to suit my needs for a hobbyist artist using ArtRage and GIMP on a Galaxy Book Flex

See below for my layout and a lights out theme which matches the lights out theme in ArtRage 👍 

[artrage.zip](https://github.com/Martenfur/TabletFriend/files/7454305/artrage.zip)

and an annotated image of what each button does

![tabletfriend_artrage](https://user-images.githubusercontent.com/93537117/139697293-eba3cf73-6b8b-4e91-9fd8-9887a399299e.jpg)

**Comment by Martenfur** [comment]
Modified the toolbar a little bit and packed it with the app by default. Thanke :D
