### ISSUE TITLE
examples of new features that can be added to - tablet friend

### ISSUE THREAD

**Issue by lpslp** [Martenfur/TabletFriend#24]
hi Martenfur
your program have good start point but! take a look at this videos - there you can see how other programs like your works with DRAW program...
there you can get an idea about enhancements - understanding how people, who want to use your program with photoshop _actually_ use programs - what they expect...

1- https://www.youtube.com/watch?v=XZTmbsopAmk Touchkey is the best!
   _a_- in Touchkey you can press and hold the button with your finger while you SIMULTANEOUSLY do something with the stylus - that is, the area under the tockey window stops processing the stylus and processes pressing and holding with your finger!
   _b_- in Touchkey when you bring the stylus to her window - the window hides - so that you can draw comfortably under her window. But your program not only hides but also handles stylus presses.

2- https://www.youtube.com/watch?t=300&v=STH83j24aic&feature=youtu.be Toolbar Creator less compatibility with tablets but still - look at hot is setup

3- https://www.youtube.com/watch?t=1174&v=Riie8jhrGCQ&feature=youtu.be panel based on autohotkey and compiled in exe - take a look at how he is draw and press button AT THE SAME TIME + touch slider like in old intuos tablets...

please you have a good start - but bring "to mind" your program.

**Comment by Martenfur** [comment]
Sorry, my boy, but I have far more important projects than this one, I can barely spare the time to look at PRs even. I am quite happy with its current state, the main point of tabletfriend is to be easy to use, easy to set up and good-looking. If you want to implement new features, go ahead, nothing's stopping you.
