### ISSUE TITLE
add visibility only  is left or right or top or bottom

### ISSUE THREAD

**Issue by MichelReims** [Martenfur/TabletFriend#25]
Hello,
Your software is very well. I use it with my surface pro and Xournalpp.
How is it possible to add visibility option of button only if board is on right, or is on left, or is on top , or is on bottom.
It is usefull when I change position of bar fo
; Then I can change size of buttons

**Comment by Martenfur** [comment]
A little bit late, I know, but I've added this feature. Now you can use `docked_left`, `docked_right` and `docked_top` options in `visibility` property. 
This feature will be in 2.0 release.
