### ISSUE TITLE
Unbindable key?

### ISSUE THREAD

**Issue by ZeroKarmaa** [Martenfur/TabletFriend#30]
Hi, love your work, super useful and easy to use.
However it seems like I can't bind my " à " key (I'm Italian e we do have those in our Keyboard Layout, for example i use them to increase the size of the brush on photoshop).
Is there any way to tell the program that the shortcut is that? 
I tried with:

brush_bigger:
		action: à
		size: 3,2
		style: accent
		icon: files/icons/brush_plus2.png
		text: bigger brush
and with: 

brush_bigger:
		action: &Agrave;
		size: 3,2
		style: accent
		icon: files/icons/brush_plus2.png
		text: bigger brush
Solutions?

**Comment by ZeroKarmaa** [comment]
Ok, just because I'm realizing I'm really bad at this, what are the two keys on the right of your " L " button? And how would I have to write them in .yaml?

**Comment by Martenfur** [comment]
Try oem_open_brackets and oem_close_brackets. Or if this doesn't work oem_semicolon and oem_quotes

**Comment by ZeroKarmaa** [comment]
OK! oem_quotes was the one! Now I'll use the list ton find the other one.
Thanks a lot man!
