### ISSUE TITLE
TabletFriend with Cintiq

### ISSUE THREAD

**Issue by scumbles** [Martenfur/TabletFriend#31]
I love TabletFriend- thank you. I use it with artist software (Rebelle 6 right now) on a 3 monitor setup including an older Cintiq 22HD (with no touch screen). The Wacom 'on-screen shortcuts' software is awful so I went hunting and found TabletFriend. It's exactly what I needed. I also use a 'Tourbox' controller with my non-dominant hand.
Since I stab and poke the buttons on TabletFriend with my stylus it sometimes moves and jumps. It would be great if I could lock it down - as you can see in the pictures I keep it inside the workspace of the software, not docked outside.
That's really my only issue. Other ideas that would be helpful for my use case would be to have layouts linked to applications. (For example the layouts in my Tourbox controller software can seamlessly switch from Rebelle to Krita and back again.)
The ability to have multiple instances open at the same time would be useful.
Also allowing a second text field for tooltips if the button features text (no icon). Most of my small buttons have truncated and abbreviated labels which would benefit from a tooltip to remind me what they are. I'll be making layouts for several other software programs- Blender, Krita, etc- I can see this becoming an issue.
I have no coding experience, but I found modifying the layout enjoyable and as easy to 'get the hang of' as you described.

Screenshots of my Rebelle layouts, adapted from the default and default-mini you provided. Note how they blend in with the Rebelle tool set:
![Default-mini](https://user-images.githubusercontent.com/130703509/232166713-cb98fffa-fd50-4744-b811-ba4a3e247dff.jpg)
![Default Layout](https://user-images.githubusercontent.com/130703509/232166734-8bf383e9-7b56-401b-bb12-483b93409de9.jpg)

**Comment by Martenfur** [comment]
>That's really my only issue. Other ideas that would be helpful for my use case would be to have layouts linked to applications. (For example the layouts in my Tourbox controller software can seamlessly switch from Rebelle to Krita and back again.)

I have already implemented this feature in develop branch,  will include it in an upcoming 2.0 release. As for the rest, would be cool, but not essential. Maybe in the future.
