### ISSUE TITLE
Other instances of Tablet Friend result in 2.0 not running

### ISSUE THREAD

**Issue by MaskedEmu** [Martenfur/TabletFriend#35]
When I try to run 2.0 from the unzipped file I get three windows

"Welcome to Tablet Friend! See the https://github.com/Martenfur/TabletFriend #readme if you have any questions. Would you like to move Tablet Friend to AppData?

I click "yes"

New window. "Update: Another version of Tablet Friend detected. 'files' directory will be overwritten. Previous version's layouts, themes and icons will be moved to 'files.backup'. WARNING: If you are updating from 1.0 to 2.0, layout and theme structure has been changed. If you have your own layouts you will need to update them manually. See (same url to readme) for the instructions"

I click "yes'"

Last window "Error!: Failed to copy the files. 'The process cannot access the file 'C:\Users\me\AppData\Roaming\TabletFriend\D3DCompiler_47_cor3.dll' because it is being used by another process'. Make sure all other instances of Tablet Friend are closed and try again'."

I click "ok"

The windows then close and Tablet Friend fails to start.

I deleted every instance I could find of 1.0 I could find and pasted my old themes and layouts into the 2.0 files. However, when I start my computer, 1.0 still starts up!

How do I get rid of 1.0 so I can start 2.0 and would that even help?

Thanks

**Comment by Martenfur** [comment]
That's weird. Try this:
1. Launch 1.0 version.
2. In the context menu, click on "open layouts directory"
3. This should open Explorer exactly where 1.0 is located. Then quit 1.0 and delete all the files from it.
4. 2.0 should install normally now.

Just make sure it's not in Program Files, this folder requires admin perms and the app does not like that.

**Comment by MaskedEmu** [comment]
I tried to go through your steps only to discover that 1.0 no longer starts up when the computer turns on

I also took 2.0 out of the downloads folder, but this did not fix the issue.

**Comment by Martenfur** [comment]
The issue was that 1.0 starts. If is no longer starts, what's the issue?
If you're having this much trouble with it just put the program manually into Appdata anywhere and set it to autostart.

**Comment by MaskedEmu** [comment]
Thank you for your help! I went through a process to remove all of the startup files that were still lingering, removed all the newest V2 files, restarted, and then downloaded the new version again. I now have it running.

Can't wait to see all that V2 has to offer!

**Comment by MaskedEmu** [comment]
Closing as completed.
