### ISSUE TITLE
Visibility per app

### ISSUE THREAD

**Issue by dreag2121** [Martenfur/TabletFriend#36]
I just found this application and so far it is really cool and helpful. I had a few questions, I can make more tickets if necessary. 

1. Is there a way to make icons show based on app?
- I saw there is one for dock visibility. 
- I would like to just edit one of the files.
3. Is there a list of properties? 

There is the overall options that I have found:

1. layout_width
2. button_size
4. margin
5. min_opactiy
6. max_opacity
7. app
8. buttons

Then you have the button properties:
- icon
- action
- text
- font_weight
- font_size
- style
- visibility
- size
- spacer
- visibility
- icon_stretch

Is that all of them?  I have a feeling this program was just built on a known language and I am just missing where it says that.

**Comment by Martenfur** [comment]
There is a sample layout literally built in, it covers every single feature. Readme also explains a lot.
https://github.com/Martenfur/TabletFriend/blob/develop/TabletFriend/TabletFriend/files/layouts/sample_layout.yaml

As for the per-app stuff, I don't understand what you're asking.

**Comment by dreag2121** [comment]
Yup, it wasn't pretty and my brain was not having it. But I figured it out. It is all there.

The other thing was about per app butt0n instead of layout. But copy paste isn't that hard to do. 

The app is awesome.

**Comment by Martenfur** [comment]
Per-app buttons will require a ton of rework, and usually, the changes between layouts are big enough to justify having an additional layout so it's good enough.
