### ISSUE TITLE
Toolbar does not open after restarting

### ISSUE THREAD

**Issue by mlunaphillips** [Martenfur/TabletFriend#37]
The app is starting as the tray icon is showing but every time have to click on it for the toolbar to actually open.

Previous version opened right away after a restart.

**Comment by Martenfur** [comment]
Yes, that is a deliberate change. I never liked it opening by itself on start, it shouldn't do that.

**Comment by mlunaphillips** [comment]
Understood. Is there any way of changing that behavior? I have an use case in which I need the toolbar opening by itself automatically. If not I'll have to go back to the previous version.

**Comment by Martenfur** [comment]
> Understood. Is there any way of changing that behavior? I have an use case in which I need the toolbar opening by itself automatically. If not I'll have to go back to the previous version.

No, not really, it's autoclosed now and you can't change it without changing the code. You can add the option and make a pull request, I'll approve it. Or simply compile a build for yourself with that flag forced on. Right now I'm busy with other projects and don't have time to add this option.
