### ISSUE TITLE
Fn key not usable

### ISSUE THREAD

**Issue by TimoNotThy** [Martenfur/TabletFriend#42]
I've tried fn, Fn, function, Function and none of these options worked to call the function key.
The reason for using this key is to combine it with F6/F7 to dim/brighten the screen.

Is there a different way to press this key or a workaround to accomplish this?

**Comment by Martenfur** [comment]
Fn doesn't have a software keycode, so you can't press it. But, the keys for brightness must be somewhere in the key list.
