### ISSUE TITLE
[IDEA] XP-Pen Artist 12 Pro Like "Dial Button"

### ISSUE THREAD

**Issue by CarJem** [Martenfur/TabletFriend#46]
I currently use TabletFriend a lot with Krita, and I love it, and I had an idea that I feel would contribute to it's ever increasing usability, the image below showcases the buttons on the XP-Pen Artist 12 Pro, including the Red Dial. 

My idea is to implement a special button type that could emulate the effect. Rotating the "dial" button in one direction would activate one action, rotating it the other direction would trigger another. It could be used as a scroll wheel, a means of zooming in and out, rotating a canvas, and so much more if implemented. Hopefully, this idea is something that could be considered for the utility!

![image](https://github.com/Martenfur/TabletFriend/assets/18092668/32daff20-caa5-481d-8950-c5806ac2ae4e)

**Comment by Martenfur** [comment]
Dials would be too hard to add, and would probably be very janky.
