### ISSUE TITLE
Opacity Bug

### ISSUE THREAD

**Issue by Marcowar1985** [Martenfur/TabletFriend#49]
The entire thing vanishes in float mode, the opacity turns to like 10? Making it impossible to see what key to press, making it completely useless. This needs to be addressed due to looking like a promising little hotkey software.

**Comment by Martenfur** [comment]
This is not a bug, this is intended behavior. Open layout file, find `min_opacity` and set it to 1 if you want it to be completely solid.

**Comment by Marcowar1985** [comment]
Thanks, there was no option called min_opacity, but manually putting it in solved the problem. Thank you.
